[package]
name = "clipcrab-ingest"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
ffmpeg-next = "8.0.0"
opencv = { version = "0.98.0", features = ["clang-runtime"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
