[workspace]
members = ["clipcrab-detect","clipcrab-ingest"]

[package]
name = "clipcrab"
version = "0.1.0"
edition = "2024"

[dependencies]
clipcrab-detect = { path = "./clipcrab-detect" }
opencv = "0.97.2"
image = "0.25.9"
tracing-subscriber = "0.3.22"
